### ISSUE TITLE
The service listener fires the ServiceStatus.lost event in about several minutes after the remote service is off.

### ISSUE THREAD

**Issue by KonstantinKolesnik** [sebastianhaberey/nsd#25]
### Description

After the remote service in the local network is down, the Lost event from the listener comes in about 5 minutes.
Is this an expected behavior?
It's almost unacceptable for the specific of my app.

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

macOS

**Comment by sebastianhaberey** [comment]
Yes, this is inherent in DNS-SD and it's the expected behavior if the remote service doesn't actively unregister. In that case it will take a while for the DNS record to time out.

Unfortunately, this will not always be avoidable, even if the application unregisters the service properly. It still happens: for example, if you force-kill a macOS application, or terminate an Android application.

A solution to overcome this could be to "ping" or "handshake" every matching service before you present it to the user as available.
