### ISSUE TITLE
com.apple.developer.networking.multicast iOS entitlement question

### ISSUE THREAD

**Issue by arazinger** [sebastianhaberey/nsd#35]
### Description

Hi,
anyone knows if **com.apple.developer.networking.multicast** entitlement is required when using this plugin on iOS 14+?
Similar plugin (https://pub.dev/packages/multicast_dns) requires it.

### Scenario

Other (please describe above)

### Platform

iOS

**Comment by sebastianhaberey** [comment]
Since I don't have an up-to-date iPhone I can only confirm that the example app runs on the CI on a simulated iPhone 11, iOS 16.0 without that entitlement. 

```
 [✓] Connected device (3 available)
    • iPhone 11 (mobile) • 85571F78-9764-4236-AAA2-2DAA0C491380 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 
```

So my guess would be no, it's not required. But of course the simulator might differ from the actual device, and also the Android version requires a similar permission, so I'll leave this open a little longer, hoping for input from actual users.

**Comment by arazinger** [comment]
Thanks!
Yes, simulator differs from actual physical device as it does not require the entitlement to test this feature.
See here for more info: https://developer.apple.com/news/?id=0oi77447

**Comment by sebastianhaberey** [comment]
From the link you provided it would make sense that the _nsd_ plugin does not need the entitlement since it uses Bonjour / mDNS:

> Apple platforms provide built in support for a cross-platform discovery protocol, Bonjour, which is also referred to as “multicast DNS”, “mDNS”, or “DNS service discovery” on other platforms. Bonjour is built into every major platform.

As far as I know, the _multicast_dns_ plugin uses a low-level multicast layer written in pure Dart, that is the same on every platform. This would probably be "custom multicast" as mentioned the following paragraph:

> Maintaining compatibility with some legacy devices and software might require the use of custom multicast and broadcast protocols. Since these capabilities give your app complete access to the user’s local network, such access requires the com.apple.developer.networking.multicast restricted entitlement.

**Comment by sebastianhaberey** [comment]
I am closing this now since there hasn't been any feedback from other users regarding the entitlement. I think we can reasonably assume the entitlement is currently not needed.
