### ISSUE TITLE
Support for IP addresses

### ISSUE THREAD

**Issue by sebastianhaberey** [sebastianhaberey/nsd#7]
This seems to be a common request, so I'm adding this issue for discussion. I'm still unsure if IP addresses should be part of this API, or if they are out of scope. My understanding is that connecting to a resolved service can and should be done using the host name / port combination. Apple representative "Eskimo" [writes on their developer forum](https://developer.apple.com/forums/thread/673771):

>  When you’re done with the resolve operation **don’t build the URL with IP addresses based on the addresses property**. Rather, build a URL with a DNS name based on the hostName property. This is easier and it’ll work better in various edge cases.

So I'd like to hold out implementing this feature until I'm more certain about its use cases. Feel free to comment here.

**Comment by sebastianhaberey** [comment]
This seems to be a common request, so I'm adding this issue for discussion. I'm still unsure if IP addresses should be part of this API, or if they are out of scope. My understanding is that connecting to a resolved service can and should be done using the host name / port combination. Apple representative "Eskimo" writes on their developer forum:

>  When you’re done with the resolve operation **don’t build the URL with IP addresses based on the addresses property**. Rather, build a URL with a DNS name based on the hostName property. This is easier and it’ll work better in various edge cases.

So I'd like to hold out implementing this feature until I'm more certain about its use cases. Feel free to comment here.

**Comment by guyluz11** [comment]
If you are searching for use case examples we are here.
[vernet](https://github.com/git-elliot/vernet) is Network Analyzer and Monitoring Tool.

It currently shows the users all devices IPs on the local network.
We can use one of two options in order to show the user device mDNS name with his IP.

1. Get mDNS name (if exist) of specific IP, as we already have all the devices IP in the local network.
2. Get a list of all the mDNS in the local network compare it to our list by IP and add the name for it.

You can see an example for the result in a close source app named [Network Scanner](https://play.google.com/store/apps/details?id=com.myprog.netscan)

**Comment by sebastianhaberey** [comment]
Since this feature seems somewhat popular, I will have a look at adding an option to look up IPs.

**Comment by sebastianhaberey** [comment]
The latest version (1.3.0) now has an `ipLookupType` flag:

```Dart
final discovery = await startDiscovery(serviceType, ipLookupType: IpLookupType.any);
```

This will populate the new attribute `service.addresses` with the addresses of the service host.
