### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lvsecoto** [sebastianhaberey/nsd#9]
Thank! This plugin is great. 

And I also need Windows support. 

I think it would be difficult...

Here are documents of Windows API. Thanks!

> win32
> https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsservicebrowse
> https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsserviceregister

> uwp
> https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd

**Comment by sebastianhaberey** [comment]
Windows support is definitely the next big feature I'd like to implement. Unfortunately I don't have access to a Windows machine right now (I might have by end of March).

**Comment by lvsecoto** [comment]
> Windows support is definitely the next big feature I'd like to implement. Unfortunately I don't have access to a Windows machine right now (I might have by end of March).

Thank you~ I am look forward to your big feature~

**Comment by lxp-git** [comment]
I am trying to finish it. No error handling. Code clean is needed also. I will do that later.

https://github.com/lxp-git/nsd/commit/fa2827d2e2a6c079c35080c8b2689b2899a45847

**Comment by sebastianhaberey** [comment]
That's good news! If you like, you can publish your _nsd_windows_ as [endorsed federated plugin](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#endorsed-federated-plugin) once you're done. It's pretty easy to do, if you have an account on pub.dev. If it passes the integration test, I'll endorse it by adding the dependency to the plugin. That way, you'll be the maintainer of _nsd_windows_ in your own repository, and the plugin will support windows.

**Comment by lxp-git** [comment]
I published my first version on Pub.  Some issues still have.
1. onServiceDiscovered callback repeatly.
2. No onServiceLost found in native windows API.
I will continue to work hard.

**Comment by sebastianhaberey** [comment]
Great! Have you tried running the integration tests with it? They should run out of the box, since they are platform independent. In Android Studio, right click `nsd` > `example` > `integration_test` > `test.dart` and select `Run`. This should run the existing integration tests on whatever platform is selected in the IDE.

Once the example application works as intended and the integration tests pass, I'll gladly add the dependency to the main project.

Also, I'll try to set up the integration tests for Windows using Github actions, as I did for the other platforms. This will enable me to run the integration test on the CI whenever a new version of your plugin is released.

**Comment by sebastianhaberey** [comment]
Sorry, I did not take into account that there needs to be a Windows runner in the example application too. So I've created a new branch `nsd_windows_endorse` that has a basic Windows runner created with `flutter create`.

You can see the result of running the integration test against version 1.0.0 [here](https://github.com/sebastianhaberey/nsd/runs/5165945492?check_suite_focus=true).

As you can see, the test does not compile currently. I am convinced this requires some minor tweaking on my side, in `nsd/example/windows`. Unfortunately I cannot fix this, since I don't have Windows.

I suppose that your `nsd/example/windows` is already working? If so, I'll gladly take any suggestions / pull request for this directory.

**Comment by lxp-git** [comment]
@sebastianhaberey 
1. I checkout your branch and tried running the integration tests. It works well. Six tests
2. I noticed that you are using Microsoft Windows [Version 10.0.17763.2458]. As my searched results, native mdns was introduced in the version 10.0.18362.0 (1903/19H1) of Windows SDK. 
3. I also delete `/WX /wd"4100"` in `CMakeLists.txt` since it treat warning as error.

**Comment by sebastianhaberey** [comment]
That's good news! I updated the test environment to Windows Server 2022 (before, it was Windows Server 2019). There's only [the choice between Windows Server 2022, 2019 and 2016](https://github.com/actions/virtual-environments#github-actions-virtual-environments). 

It compiles now, but the [tests don't seem to complete](https://github.com/sebastianhaberey/nsd/runs/5166441193?check_suite_focus=true).

Do you have any ideas how to make them complete?

**Comment by sebastianhaberey** [comment]
No worries! Let me know whenever you're ready - there's no hurry.

**Comment by sebastianhaberey** [comment]
Good news! I've finally released a proper Windows version of the plugin. It now passes all the integration tests, so it should have the same behavior as the other platform plugins. I would like to say a big thank you 💕 for writing your prototype. It was invaluable when I wrote the plugin, especially dealing with the immensely clunky Windows DNS API. If you hadn't implemented a great part of the functionality already, I'd probably have taken double the time to finish the plugin.

I've made a small "contributors" section in the readme, and you're the first major contributor 😊 Thanks again!

**Comment by lijy91** [comment]
I think you should add @lxp-git  as a contributor since [nsd_windows](https://github.com/leanflutter/nsd_windows) is actually developed by it.

**Comment by sebastianhaberey** [comment]
Yes, fixed it, thank you!

**Comment by lxp-git** [comment]
@sebastianhaberey I'd like to transfer nsd_windows of pub.dev to you if you need it.

**Comment by sebastianhaberey** [comment]
Hey thanks, do you know if that's possible? If yes, I'd be glad to use it.

**Comment by lxp-git** [comment]
@sebastianhaberey I invite you as a uploader. Please accept the invitation. I will delete my self email if you ready. Maybe it will work.

**Comment by sebastianhaberey** [comment]
Nice, that actually worked - I could transfer the package to my own publisher. Thank you so much!
